# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SNS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod "AFNetworking", "~> 2.0"
  pod "AFNetworkActivityLogger", "~> 2.0"
  pod 'SVProgressHUD'
  pod 'RMUniversalAlert',        '~> 0.7'
  pod 'RDVTabBarController',      '~> 1.1.3'
  pod 'Facebook-iOS-SDK'
  # Pods for SNS

end
